name: Publish Package
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build -- ngx-fluent

      - name: Switch directory to dist lib
        run: cd dist/ngx-fluent

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
